Repository J-AGGERHOLM/OenskeListen, pull requests merged in 2025-03, with the labels that each got.

#32 Sql folder
  SqlCode/create_wishlist_db.sql
  SqlCode/populate_wishlist_database.sql
Labels: documentation

#36 Spring profiles set up and repository class for Wish
  pom.xml
  src/main/java/Repository/WishRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: System

#47 Index test
  src/main/java/org/example/oenskelisten/Controller/UserController.java
  src/main/resources/templates/index.html
Labels: good first issue, Database

#49 java version set to 21
  pom.xml
Labels: System

#50 Java version set to 21 in qodana_code_quality.yml
  .github/workflows/qodana_code_quality.yml
Labels: System

#51 get all users method done and service layers set up.
  src/main/java/org/example/oenskelisten/Controller/UserController.java
  src/main/java/org/example/oenskelisten/Model/Person.java
  src/main/java/org/example/oenskelisten/Model/UserRowMapper.java
  src/main/java/org/example/oenskelisten/Repository/UserRepository.java
  src/main/java/org/example/oenskelisten/Service/UserService.java
  src/main/resources/application-dev.properties
Labels: Programming

#52 Lavet lidt ændringer
  src/main/java/org/example/oenskelisten/Controller/UserController.java
  src/main/java/org/example/oenskelisten/Exception/GlobalException.java
  src/main/java/org/example/oenskelisten/Interface/IRepository.java
  src/main/java/org/example/oenskelisten/Interface/IUserRepository.java
  src/main/java/org/example/oenskelisten/Model/Person.java
  src/main/java/org/example/oenskelisten/Model/User.java
  src/main/java/org/example/oenskelisten/Model/UserRowMapper.java
  src/main/java/org/example/oenskelisten/Repository/BaseRepository.java
  src/main/java/org/example/oenskelisten/Repository/UserRepository.java
  src/main/java/org/example/oenskelisten/Repository/WishRepository.java
  src/main/java/org/example/oenskelisten/Service/UserService.java
Labels: Programming

#65 person-methods
  src/main/java/org/example/oenskelisten/Controller/UserController.java
  src/main/java/org/example/oenskelisten/Interface/IRepository.java
  src/main/java/org/example/oenskelisten/Model/User.java
  src/main/java/org/example/oenskelisten/Repository/UserRepository.java
  src/main/java/org/example/oenskelisten/Service/UserService.java
  src/main/resources/templates/new-user-form.html
  src/main/resources/templates/userPage.html
  src/main/resources/templates/users.html
Labels: Programming

#64 Classes, models, and html templates for WishList features
  src/main/java/org/example/oenskelisten/Controller/UserController.java
  src/main/java/org/example/oenskelisten/Controller/WishListController.java
  src/main/java/org/example/oenskelisten/Interface/IRepository.java
  src/main/java/org/example/oenskelisten/Interface/IWishListRepository.java
  src/main/java/org/example/oenskelisten/Model/Wish.java
  src/main/java/org/example/oenskelisten/Model/WishList.java
  src/main/java/org/example/oenskelisten/Repository/UserRepository.java
  src/main/java/org/example/oenskelisten/Repository/WishListRepository.java
  src/main/java/org/example/oenskelisten/Service/UserService.java
  src/main/java/org/example/oenskelisten/Service/WishListService.java
  src/main/resources/static/css/stylesheet.css
  src/main/resources/templates/addWish.html
  src/main/resources/templates/editWish.html
  src/main/resources/templates/wishListItem.html
  src/main/resources/templates/wishListItems.html
Labels: Programming
